### ISSUE TITLE
Ban number of rows

### ISSUE THREAD

**Issue by merinos** [CODeRUS/sailfishos-eventsview-controls-1row-volume-patch#1]
In unified_diff.patch line 48 you have the following line : 
`Math.ceil(objectsCount / 4)`

This doesn't work beacause objectsCount / 4 will return a truncate integer instead of a float. For example if I have 6 icons objectsCount / 4 will return 1 instead of 1.5.

To fix this I think you must replace the fllowing line Math.ceil(objectsCount / 4) by :
`Math.ceil(objectsCount / 4.0)`

**Comment by CODeRUS** [comment]
This is very old and outdated patch, this one is better version: https://github.com/CODeRUS/sailfishos-eventsview-controls-remastered-patch
But thanks anyway for suggestion :)
